# Group Adoption


**Due**: Friday April 23, with PS4. 

You are to work together on this problem with your current working groups. This will be part of the problem set after the midterm. 

Each team is given a group of order 12 to adopt.  Your assignment is to make a catalog of the important properties of that group. This should include:

a. Figuring out what the 12 elements are.
a. Computing the Cayley table
a. Building the subgroup lattice (start with the cyclic groups and add to them)
a. Finding the center and the centralizer of each element
a. Finding all normal subgroups N and describing the quotient G/N
a. Making the Cayley graph with respect to your given generators.
a. You will each do your work in a shared Overleaf document. Here is a [template](https://www.overleaf.com/project/606e03d9989ca25369d03732) for a group of order 12.  You should make a copy of this and share it with your group members. Here are the answers worked out for the [dihedral group D3](https://www.overleaf.com/read/nkncqqjssgrk).

Here are the group assignments

## The Blue Group $B_{12}$

The group $B_{12}$ is the subgroup of $GL_3(\RR)$ generated by 
$$
A = 
\begin{bmatrix} 
0 & 0 & 1 \\
1 & 0 & 0 \\
0 & 1 & 0 \\
\end{bmatrix} 
\qquad\hbox{and}\qquad
B = 
\begin{bmatrix} 
0 & 1 & -1 \\
1 & 0 & -1 \\
0 & 0 & -1 \\
\end{bmatrix} 
$$

## The Green Group $G_{12}$

The group $G_{12}$ is generated by $a$ and $b$ subject to the relations
$$
a^6 = b^2 = (ab)^2 = 1
$$

## The Orange Group $O_{12}$

The orange group $O_{12}$ is the subgroup of $GL_2(\mathbb{C})$ generated by the matrices
$$
A = 
\begin{bmatrix} 
\omega & 0  \\
0 & \omega^{-1}  \\
\end{bmatrix} 
\qquad\hbox{and}\qquad
B = 
\begin{bmatrix} 
0 & 1 \\
1 & 0  \\
\end{bmatrix} 
$$


## The Purple Group $P_{12}$

The group $P_{12}$ is generated by $s$ and $t$ subject to the relations
$$
s^6 = 1, \quad t^4 = 1, \quad aba = b.
$$

## The Red Group $R_{12}$



## The Yellow Group $Y_{12}$.
