# (PART) Problem Sets {-}

\newcommand{\ZZ}{\mathbb{Z}}
\newcommand{\RR}{\mathbb{R}}
\newcommand{\QQ}{\mathbb{Q}}
\newcommand{\CC}{\mathbb{C}}
\newcommand{\G}{\mathsf{G}}
\newcommand{\H}{\mathsf{H}}

# Problem Set 1 

**Due**: Friday March 26, 5:00PM CST. 

* You should upload your assignment under the PS1 link on Moodle. 
* You can hand write your solutions and scan them, or typeset them in R or LaTex. But you should upload the assignment in a single PDF or a single HTML file. 
* Ideally, submit the problems in order, but if that is not possible, the problems should be clearly labeled.
* You should **justify** all answers, unless the assignment is to *compute* something. Then you should clearly display your computed work. 
* All assignments will be out of **30 points**. For example, this assignment has six 5-point problems. 
* **Late work**: assignments will be lowered by 10% each day they are late. The solution will be posted on Tuesday. From that point on, I will still accept assignment write-ups, but you can earn a maximum of half of the points.
* **Collaboration** is encouraged. In fact, it has been shown that people who form study groups, and talk about assignments, learn more and perform better. However, you should write up your own work in your own words (blatent copying is not acceptable), and if you receive substantial help from a classmate, you should give that person credit in your write-up (no pentalty for this!).

## Modular Multiplication

Make the *multiplication* tables of the following sets and determine which of them are groups under multiplication:

a. $\{1,2,3\}$ using multiplication mod 4
b. $\{1,2,3,4\}$ using multiplication mod 5
c. $\{1,5,7,11\}$ using multiplication mod 12
d. $\{5,15,25,35\}$ using multiplication mod 40

## Group of Units $U_n$ mod n

Let $U_n = \{1 \le k < n \mid 1 = \gcd(k,n) \}$. These are the elements of $\ZZ_n$ that are relatively prime to $n$. Note: the book denotes this by $U(n)$.

a. Compute the sets $U_6,U_7,U_8$.

b. Use the R-code in [Modular Arithmetic] to do the following (you can do it by hand if you prefer).

    i. Make the multiplication tables of $\ZZ_8$ and $U_8$ mod 8.
    ii. Make the multiplication table of $U_9$.
    iii. Make the multiplication table of $U_{14}$.

c. We will show that $U_n$ is a **group** under *multiplication* mod n. Multiplication mod n is **associative** so we don't need to do that, and the multiplicative **identity** $1$ is in $U_n$, since $gcd(n,1) = 1$.  Show that if $a \in U_n$ then $a$ has a multiplicative **inverse** in $U_n$. Do this by using the Extended GCD from Chapter 0 (the Extended GCD also appears in the VoiceThread on Cyclic Groups).

d. Show that $U_n$ is closed under multiplication. That is if $a, b \in U_n$, then $ab \in U_n$. This shows that multiplication mod $n$ is a **binary operation** on $U_n$. Hint: if $a$ is invertible mod n and $b$ is invertible mod n, then must $ab$ be invertible mod $n$; think about your shoes and socks.

e. Are $U_8$, $U_9$, and/or $U_{14}$ cyclic? Justify your answers.

## Two-by-two mod 2

The group $GL_2(\ZZ_2)$ is the group of all invertible $2\times 2$ matrices with entries from $\ZZ_2 = \{0,1\}$ and all arithmetic done mod 2. That is,
$$
GL_2(\ZZ_2) =
\left\{
A=\begin{pmatrix} a & b \\ c & d \end{pmatrix} 
\mid a,b,c,d \in \{0,1\} \hbox{ and $A$ is invertible}
\right\}.
$$
The operation is usual matrix multiplication with arithmetic done mod 2 so that: 0+0 = 0, 0+1 = 1+0 = 1, 1+1 = 0. 

a. There are 16 matrices of this form (two choices 0 or 1 for each of the four matrix entries), determine which of these are invertible (you can use the determinant mod 2). 

b. Let $A$ and $B$ be the matrices below
$$
A = \begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix} \qquad\hbox{and}\qquad
B = \begin{pmatrix}  1 & 1 \\ 0 & 1 \end{pmatrix}.
$$
Show that every element in this group is of the form $A^i B^j$ for some powers $i$ and $j$ (these powers can be 0).

c. Since $BA$ is in the group, it must be equal to $A^i B^j$ for some $i$ and $j$. Find $i$ and $j$.


## Outer Cancellation

A group $\G$ has the special property that for all $x,y,z \in G$, if $xy = zx$ then $y = z$. Prove that $\G$ is abelian.



## Distributing Powers

Prove that for $a, b$ in a group $\G$ we have
$$
(ab)^2=a^2b^2
\quad \hbox{ if and only if } \quad 
ab=ba.
$$

## Cyclic Subgroups

If $g \in \G$, then $\langle g \rangle \le \G$ is the smallest subgroup of $\G$ that contains $g$. We will show in class that 
$$
\begin{array}{rcll}
\langle g \rangle &=& \{ g^k \mid k \in \ZZ\}, & \hbox{if $|g| = \infty$}.\\
\langle g \rangle &=& \{1, g, g^2, \ldots, g^{n-1}\}, \quad  &  \hbox{if $|g| = n$}.\\
\end{array}
$$
Compute the elements of the following cyclic subgroups.

a. $\langle 5 \rangle  \le \ZZ$
a. $\langle 5 \rangle \le \ZZ_{30}$
a. $\langle 5 \rangle \le \RR^\ast$
a. $\langle 5 \rangle \le U_{28}$
a. $\langle (\frac{\sqrt{2}}{2} + \frac{\sqrt{2}}{2}i) \rangle  \le \CC^\ast$


