# Problem Set 3


**Due**: Friday April 9, 5:00PM CST. 

* Same rules as always.

## Centralizer is a Group Invariant

Suppose that $\phi: \G_1 \to \G_2$ is a group isomorphism. Let $a \in \G_1$ and recall that the *centralizer* of $a$ in $\G_1$ is the subgroup
$$
C_{\G_1}(a) = \{ g \in \G_1 \mid g a = a g\} \le \G_1.
$$
Prove that $\phi(C_{\G_1}(a)) = C_{\G_2}(\phi(a))$.

## Index of the Center

Prove that in a finite group $\G$, the index of the center $[G:Z(\G)]$ cannot be prime. (Hint: let $a \in \G \setminus Z(\G)$ and consider the centralizer $C_\G(a)$).

## Quaternion Quotient

Recall the quaternion group $Q_8 = \{1,-1,i,-i,j,-j,k,-k\}$. 

a. Show that $H = \{1,-1\}$ is a normal subgroup of $Q_8$.

a. The quotient group $Q_8/H$ has order 2. You have proved that, up to isomorphism, there are two groups of order 4. They are $\mathbb{Z}_4$ and the Klein-4 group $K_4 = \mathbb{Z}_2 \times \mathbb{Z}_2$. Which of these two groups is $Q_8/H$ isomorphic to?

## Fermat's "Little" Theorem

The point of this problem is to show that many of the interesting and important properties of modular arithmetic and coding theory actually come from group theory. 

Recall that $U(n) = \{ 1 \le k < n \mid \gcd(k,n) = 1\}$ is the group of units under multiplication mod $n$. Let $\phi(n) = |U(n)|$, so that $\phi(n)$ is the number of positive integers less than $n$ that are relatively prime to $n$. 

Use the corollaries of Lagrange's Theorem to give short proofs of the facts below.

a. Fill out the table
$$
\begin{array}{|c|ccccccccccc|}
\hline
n & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12 \\
\hline
\phi(n) & & &&&&&&&&& \\
\hline
\end{array}
$$

b. Prove that $a^{\phi(n)} \equiv 1  (\mathsf{mod}\ n)$. (Hint: use a corollary of Lagrange's Theorem).

c. Demonstrate that b works for $n = 12$ and each $a \in U(12)$.

d. Show that a special case of b is the following, which is called *Fermat's Little Theorem*: $a^{p} \equiv a (\mathsf{mod}\ n)$ for a prime number $p$.

e. Demonstrate Fermat's Little Theorem for $p = 7$ and each number in $U(7)$.




