# Problem Set 4


**Due**: Wednesday April 28, midnight CST. Time will be provided *in class* to work on these and discuss them with your peers. This problem set has 4 problems.

## Boolean Rings

Let $R$ be a ring in which $a^2 = a$ for every $a \in R.$

a. Prove that $a = -a$ in this ring.

b. Prove that $R$ is commutative. (Hint: cleverly use the $a^2 = a$ property and don't forget that we have addition in $R$ but we don't have cancellation).

c. Prove that if $R$ has unity and $a \not= 0,1$ then $a$ is a zero divisor.

d. $\ZZ_2 =\{0,1\}$ is a Boolean ring with 2 elements. Give an example of a Boolean ring with unity having 4 elements. 

## Subsets, Subrings, and Ideals

Each example below describes a subset $S \subseteq R$. Determine (with proof) whether $S$ is "just" a subset or is a subring or is an ideal. 

a. $R = \ZZ[x]$ and $S$ is the set of polynomials with 0 constant term: $S = \{ p(x) = a_0 + a_1 x + \cdots + a_n x^n \in \ZZ[x] \mid a_0 = 0\}$.

b. $R = \ZZ[x]$ and $S$ is the set of polynomials with an even constant term: $S = \{ p(x) = a_0 + a_1 x + \cdots + a_n x^n \in \ZZ[x] \mid a_0 \in 2 \ZZ \}$.

c. $R = \ZZ[x]$ and $S$ is the set of polynomials with a zero quadratic term: $S = \{ p(x) = a_0 + a_1 x + a_2 x^2 + a_3 x^3 + \cdots + a_n x^n \in \ZZ[x]\mid a_2 = 0 \}$.

d. $R$ is a commutative ring, $a \in R$, and $S = \{ r \in R \mid r a = 0 \}$.

e. $R$ is a ring and $S = \{ s \in R \mid s r = r s \text{ for all } r \in R\}$.

Hint: you might want to use some ring properties in  [Definitions].

## Gaussian Quotient Ring

Let $I = \langle 2 + 2 i \rangle \subseteq \ZZ[i]$. That is, $I$ is a principal ideal in the ring of Gaussian integers. 

a. List the distinct cosets in $\ZZ[i]/I$. 

b. Find the units in $\ZZ[i]/I$. Give each unit with its inverse.

c. If $\ZZ[i]/I$ has zero divisors, give an example of one.

d. Where in the Venn diagram of rings does $\ZZ[i]/I$ live?

e. Is $I$ a prime ideal? Is $I$ a maximal ideal? In each case, say why or why not.

## Ideal Radicals

Let $R$ be a commutative ring, let $A$ be any ideal of $R$, define the radical of $A$ to be
$$
N(A) = \{ r \in R \mid r^n \in A \text{ for some positive integer } n\}
$$
(the integer $n$ can be different for different choices of $r$).

a. Prove that $N(A)$ is an ideal of $R$.
a. Give an example where $N(A) = A$ and an example where $A \subsetneqq N(A)$.
a. The nilradical of $R$ is $N(\{0\})$. Find (with proof) the nilradical of $R/N(A)$ for any ideal $A$. That is, state what it is and then prove your statement. Here is a movie ( [mov](https://drive.google.com/file/d/1Ekgp_xKZjI3CSv6EPXfjjAXawkjBY_bq/view?usp=sharing)|[pdf](https://drive.google.com/file/d/1D8--HIxqJFYapnHn_fHFGYahhVyc3gFn/view?usp=sharing)) that might clarify things.

